
# Minimal Mistakes theme
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site settings
title: "Kara Lamantia"
subtitle: "Royal Society Newton International Fellow"
url: "https://lamantiakara.github.io"

# Masthead image
logo: "/assets/images/avatar.png"

# Favicon
favicon: "/assets/images/QICsummit2.jpg"

# Author sidebar info
author:
  name: Kara Lamantia
  bio: "Royal Society Newton International Fellow at the University of Bristol Glaciology Center."
  avatar: "/assets/images/picture3.jpg"
  email: kara.lamantia@bristol.ac.uk
  location: Bristol, UK
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "github.com/lamantiakara"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=v0bt4CkAAAAJ&hl=en&oi=ao"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kara-lamantia-539023118/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0002-1448-3280"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kara.lamantia@bristol.ac.uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lamantiakara"
  since: "2026"

# Build settings
markdown: kramdown

# Include/exclude
include:
  - _pages
  - assets/images
  - assets/cv.pdf
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Hide xml feed
atom_feed:
  hide: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      header:
        overlay_image: /assets/images/QICsummit2.jpg
        overlay_filter: 0.3
        overlay_color: "#000"
        show_overlay_excerpt: false
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
    

